language: go

go:
    - "1.13"
    - tip

before_install:
    - sudo apt-get update
    - sudo apt-get install ffmpeg
    - ffmpeg -version
env:
    - GO111MODULE=on

script:
    - go test -v -tags="integration"
    - go vet ./...
